project: cs336-assignment1-basic
name: owt-stage1-lr
program: cs336_basics/train.py

method: bayes
metric:
  name: valid/loss
  goal: minimize
parameters:
  optimizer.muon_lr:
    distribution: log_uniform_values
    min: 1e-3
    max: 1e-1

early_terminate:
  type: hyperband
  max_iter: 2000
  min_iter: 500
  eta: 3
  strict: true

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "cs336_basics/configs/owt_muon2.json"
