project: cs336-assignment1-basic
name: tss-stage1-lr6
program: cs336_basics/train.py

method: bayes
metric:
  name: valid/loss
  goal: minimize
parameters:
  optimizer.muon_lr:
    distribution: uniform
    min: 0.010
    max: 0.013
  train.lr_max:
    distribution: uniform
    min: 0.004
    max: 0.005
  train.decay_steps:
    values: [300, 400, 500, 600]

early_terminate:
  type: hyperband
  max_iter: 30
  min_iter: 6
  eta: 3
  s: 2
  strict: true

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "cs336_basics/configs/tss_muon2.json"

# result: https://wandb.ai/yzctzl_/cs336-assignment1-basic/sweeps/5az6nm13