project: cs336-assignment1-basic
name: tss-stage1-lr2
program: cs336_basics/train.py

method: bayes
metric:
  name: valid/loss
  goal: minimize
parameters:
  optimizer.muon_lr:
    distribution: log_uniform_values
    min: 9e-3
    max: 1e-1
  train.lr_max:
    distribution: log_uniform_values
    min: 9e-4
    max: 1e-2

early_terminate:
  type: hyperband
  max_iter: 3000
  min_iter: 500
  eta: 3
  s: 2
  strict: true

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "cs336_basics/configs/tss_muon2.json"

# result: https://wandb.ai/yzctzl_/cs336-assignment1-basic/sweeps/yc1tgvk9/panel/5hcwykvw2